// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: UserBroker.proto
#ifndef GRPC_UserBroker_2eproto__INCLUDED
#define GRPC_UserBroker_2eproto__INCLUDED

#include "UserBroker.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace userbroker {

class UserBroker final {
 public:
  static constexpr char const* service_full_name() {
    return "userbroker.UserBroker";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status requestKNN(::grpc::ClientContext* context, const ::userbroker::knnQuery& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncrequestKNN(::grpc::ClientContext* context, const ::userbroker::knnQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncrequestKNNRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncrequestKNN(::grpc::ClientContext* context, const ::userbroker::knnQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncrequestKNNRaw(context, request, cq));
    }
    virtual ::grpc::Status requestComm(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::userbroker::rpcComm* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userbroker::rpcComm>> AsyncrequestComm(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userbroker::rpcComm>>(AsyncrequestCommRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userbroker::rpcComm>> PrepareAsyncrequestComm(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userbroker::rpcComm>>(PrepareAsyncrequestCommRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void requestKNN(::grpc::ClientContext* context, const ::userbroker::knnQuery* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void requestKNN(::grpc::ClientContext* context, const ::userbroker::knnQuery* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void requestComm(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::userbroker::rpcComm* response, std::function<void(::grpc::Status)>) = 0;
      virtual void requestComm(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::userbroker::rpcComm* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncrequestKNNRaw(::grpc::ClientContext* context, const ::userbroker::knnQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncrequestKNNRaw(::grpc::ClientContext* context, const ::userbroker::knnQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userbroker::rpcComm>* AsyncrequestCommRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userbroker::rpcComm>* PrepareAsyncrequestCommRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status requestKNN(::grpc::ClientContext* context, const ::userbroker::knnQuery& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncrequestKNN(::grpc::ClientContext* context, const ::userbroker::knnQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncrequestKNNRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncrequestKNN(::grpc::ClientContext* context, const ::userbroker::knnQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncrequestKNNRaw(context, request, cq));
    }
    ::grpc::Status requestComm(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::userbroker::rpcComm* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userbroker::rpcComm>> AsyncrequestComm(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userbroker::rpcComm>>(AsyncrequestCommRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userbroker::rpcComm>> PrepareAsyncrequestComm(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userbroker::rpcComm>>(PrepareAsyncrequestCommRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void requestKNN(::grpc::ClientContext* context, const ::userbroker::knnQuery* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void requestKNN(::grpc::ClientContext* context, const ::userbroker::knnQuery* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void requestComm(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::userbroker::rpcComm* response, std::function<void(::grpc::Status)>) override;
      void requestComm(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::userbroker::rpcComm* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncrequestKNNRaw(::grpc::ClientContext* context, const ::userbroker::knnQuery& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncrequestKNNRaw(::grpc::ClientContext* context, const ::userbroker::knnQuery& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::userbroker::rpcComm>* AsyncrequestCommRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::userbroker::rpcComm>* PrepareAsyncrequestCommRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_requestKNN_;
    const ::grpc::internal::RpcMethod rpcmethod_requestComm_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status requestKNN(::grpc::ServerContext* context, const ::userbroker::knnQuery* request, ::google::protobuf::Empty* response);
    virtual ::grpc::Status requestComm(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::userbroker::rpcComm* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_requestKNN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_requestKNN() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_requestKNN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestKNN(::grpc::ServerContext* /*context*/, const ::userbroker::knnQuery* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestKNN(::grpc::ServerContext* context, ::userbroker::knnQuery* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_requestComm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_requestComm() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_requestComm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestComm(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::userbroker::rpcComm* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestComm(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::userbroker::rpcComm>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_requestKNN<WithAsyncMethod_requestComm<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_requestKNN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_requestKNN() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::userbroker::knnQuery, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::userbroker::knnQuery* request, ::google::protobuf::Empty* response) { return this->requestKNN(context, request, response); }));}
    void SetMessageAllocatorFor_requestKNN(
        ::grpc::MessageAllocator< ::userbroker::knnQuery, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::userbroker::knnQuery, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_requestKNN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestKNN(::grpc::ServerContext* /*context*/, const ::userbroker::knnQuery* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* requestKNN(
      ::grpc::CallbackServerContext* /*context*/, const ::userbroker::knnQuery* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_requestComm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_requestComm() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::userbroker::rpcComm>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::userbroker::rpcComm* response) { return this->requestComm(context, request, response); }));}
    void SetMessageAllocatorFor_requestComm(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::userbroker::rpcComm>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::userbroker::rpcComm>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_requestComm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestComm(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::userbroker::rpcComm* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* requestComm(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::userbroker::rpcComm* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_requestKNN<WithCallbackMethod_requestComm<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_requestKNN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_requestKNN() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_requestKNN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestKNN(::grpc::ServerContext* /*context*/, const ::userbroker::knnQuery* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_requestComm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_requestComm() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_requestComm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestComm(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::userbroker::rpcComm* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_requestKNN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_requestKNN() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_requestKNN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestKNN(::grpc::ServerContext* /*context*/, const ::userbroker::knnQuery* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestKNN(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_requestComm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_requestComm() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_requestComm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestComm(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::userbroker::rpcComm* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestComm(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_requestKNN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_requestKNN() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->requestKNN(context, request, response); }));
    }
    ~WithRawCallbackMethod_requestKNN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestKNN(::grpc::ServerContext* /*context*/, const ::userbroker::knnQuery* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* requestKNN(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_requestComm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_requestComm() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->requestComm(context, request, response); }));
    }
    ~WithRawCallbackMethod_requestComm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestComm(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::userbroker::rpcComm* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* requestComm(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_requestKNN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_requestKNN() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::userbroker::knnQuery, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::userbroker::knnQuery, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedrequestKNN(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_requestKNN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status requestKNN(::grpc::ServerContext* /*context*/, const ::userbroker::knnQuery* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrequestKNN(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::userbroker::knnQuery,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_requestComm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_requestComm() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::userbroker::rpcComm>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::userbroker::rpcComm>* streamer) {
                       return this->StreamedrequestComm(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_requestComm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status requestComm(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::userbroker::rpcComm* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrequestComm(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::userbroker::rpcComm>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_requestKNN<WithStreamedUnaryMethod_requestComm<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_requestKNN<WithStreamedUnaryMethod_requestComm<Service > > StreamedService;
};

}  // namespace userbroker


#endif  // GRPC_UserBroker_2eproto__INCLUDED
